### ISSUE TITLE
[전체] 최소 몇 명의 리뷰어가 필요할까요?

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/pep8-in-korean#10]
## 문제

번역을 하면서 느낀 것은...**몇 명의 리뷰어가 과연 OK를 해야 통과하는가?** 입니다.
인생이 삼세판이란 말이 있듯이 **3명의 리뷰어**가 OK를 하는 게 좋을 것 같은데요.
실제 우리가 벤치마킹하려는 프로젝트 javascript.info 한국어 번역도 섹션마다 3명의 리뷰어를 두고 있습니다.
몇 명이 적당할 것 같은지 의견을 묻습니다.

**Comment by Ohjiwoo-lab** [comment]
저도 마크다운 문법을 잘 지켰는지, 번역에 어색함이 없는지, 실수한 부분은 없는지 이렇게 크게 3개 정도로 확인할 부분이 있으니까 리뷰어는 3명 정도가 적당할 거 같아요!

**Comment by susie-Choi** [comment]
번역 작업인 만큼 통과 기준을 높게 잡으면 작업이 지연될 것 같습니다.
따라서 저는 3명의 리뷰어들이 번역에 대하여 긍정적 의견을 낸다면, 그것은 승인될 가치가 있다고 봅니다.
이후 추가적으로 의견이 발생 할 시, 그때 다시 검토하고 수정하면 된다고 생각합니다.

**Comment by Sumin0916** [comment]
저도 3명의 리뷰어를 두고, 각각 서로 다른 주제(md문법, 번역, ...)을 맡아서 검토를 하면 좀 더 통일성 있는 프로젝트가 될 것 같습니다!

**Comment by zerosheepmoo** [comment]
## 결론
- 과반수 이상의 분들이 3명의 리뷰어를 두는 것에 찬성해주셨습니다.
- 단, md 문법은 근시일 내에 lint 를 사용할 계획이므로 md 문법에 대해 너무 민감하실 필요는 없습니다. 각자 느끼기에 어색한 부분이나, 실수한 부분, 좀 더 나은 포매팅을 자유롭게 이야기 하셔도 좋을 것 같습니다.
- 만약 리뷰어 최소 인원을 재배정해야겠다 싶은 경우 이 이슈를 재오픈합니다.
