### ISSUE TITLE
PEP8 번역 - String Quotes

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/pep8-in-korean#11]
## 참여자

번역: @zerosheepmoo 
검토
- 1차: @Sumin0916 
- 2차: @hajun-myoung 
- 3차: @zerosheepmoo

**Comment by zerosheepmoo** [comment]
## 의견 / 내용

- 단어를 보고 느끼는 건데 정기적으로 공통단어 사용에 대한 discussion 을 열어야겠습니다.
    - 이는 메신저 툴 선정을 완료한 다음에 이를 해결할 수 있는 채널을 생성합시다.
- Python 의 경우 Python 을 유지할지 파이썬이라고 읽는 그대로 번역할지 고민입니다. 토의 후 용어집에 확실히 하는 것이 좋겠습니다. 우선 이곳은 영어로 해놓았습니다.
- 따옴표라 번역하지 않고 쿼트라고 번역한 이유는...나라마다 [인용부호가 다르기 때문](https://en.wikipedia.org/wiki/Quotation_mark)입니다. 우리는 반점모양을 쓰지만 프로그래밍 언어에서 쿼트는 일반적으로 ' 나 " 처럼 일자입니다. 한창 처음 언어를 배울 때 "왜 따옴표를 넣어서 출력했는데 안돼는 거지?" 했던 기억이 있어 이에 대한 혼동을 없애기 위한 번역이라 생각했는데....가독성이 안좋으면 인용부호 및 따옴표로 바꾸겠습니다 :( 1차 리뷰어 분께서 의견주세요.
- 독스트링은 독스트링이라 번역하였습니다

**Comment by Sumin0916** [comment]
> ## 의견 / 내용
> * 단어를 보고 느끼는 건데 정기적으로 공통단어 사용에 대한 discussion 을 열어야겠습니다.
>   
>   * 이는 메신저 툴 선정을 완료한 다음에 이를 해결할 수 있는 채널을 생성합시다.

저도 같은 생각입니다 조금이라도 빨리 토의를 할 수 있는 환경을 만들면 좋을 것 같아요

> * Python 의 경우 Python 을 유지할지 파이썬이라고 읽는 그대로 번역할지 고민입니다. 토의 후 용어집에 확실히 하는 것이 좋겠습니다. 우선 이곳은 영어로 해놓았습니다.

넵 이것도 추후 따로 토의를 해봐야하는 문제인 것 같네요....
저는 개인적으로 Python이라고 쓰는것이 좀 더 직관적이고 읽는이에게 전달이 더 잘 되는 것 같은 느낌이 들긴합니다!

> * 따옴표라 번역하지 않고 쿼트라고 번역한 이유는...나라마다 [인용부호가 다르기 때문](https://en.wikipedia.org/wiki/Quotation_mark)입니다. 우리는 반점모양을 쓰지만 프로그래밍 언어에서 쿼트는 일반적으로 ' 나 " 처럼 일자입니다. 한창 처음 언어를 배울 때 "왜 따옴표를 넣어서 출력했는데 안돼는 거지?" 했던 기억이 있어 이에 대한 혼동을 없애기 위한 번역이라 생각했는데....가독성이 안좋으면 인용부호 및 따옴표로 바꾸겠습니다 :( 1차 리뷰어 분께서 의견주세요.
> * 독스트링은 독스트링이라 번역하였습니다

저는 ' 작은 따옴표, " 큰 따옴표, """ 삼중 따옴표로 번역하는게 좋을 것 같다고 생각을 해보았습니다. 물론 나라마다 주로 사용하는 인용기호 표기법이 다르지만.... 코드를 작성할 때 특수문자에서 반점을 꺼내 사용하지 않는 한 키보드에서 누르면 기본적으로 일자 따옴표가 입력이 되기 때문에 그 부분은 그렇게 신경을 안써도 될 것 같다고 생각해보았습니다. 그리고 결정적으로 공통 단어 스프레드시트에 헷갈릴만한 문자를 정리해두면 추후에 읽는 사람들이 참고해서 혼동을 최대한 줄일 수 있을 것 같습니다!

**Comment by zerosheepmoo** [comment]
@Sumin0916

확인하였습니다.

- 토의 환경은 오늘 중으로 구성할 계획입니다.
- 인용부호에 대해서 동의합니다. 그렇게 수정해주세요 :)

**Comment by zerosheepmoo** [comment]
# 단어 추출 목록

단어 | 뜻
-- | --
single-quoted string | 작은 따옴표 문자열
double-quoted string | 큰 따옴표 문자열
triple-quoted string | 삼중 따옴표 문자열
backslashes | 백슬래쉬

**Comment by hajun-myoung** [comment]
## 2차 검토
코멘트 모두 달았습니다. 확인 바랍니다! :smile:

**Comment by zerosheepmoo** [comment]
# 3차 검토 내역

> 따옴표 문자 자체를

- 표현이 부자연스럽습니다. 우리나라는 따옴표가 어짜피 작은 따옴표, 큰 따옴표 밖에 없으므로 위 같이 작성합니다.

**Comment by zerosheepmoo** [comment]
모두의 동의하에 클로즈합니다.

**Comment by Sumin0916** [comment]
동의합니다!

**Comment by hajun-myoung** [comment]
저도 동의합니다!
