### ISSUE TITLE
PEP8 번역 - Whitespace in Expressions and Statements

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/pep8-in-korean#12]
## 참여자

- 번역: @zerosheepmoo 
- 검토
  - 1차: @Sumin0916
  - 2차: @Ohjiwoo-lab 
  - 3차: @hajun-myoung

**Comment by zerosheepmoo** [comment]
# 단어 추출 목록
단어 | 뜻
-- | --
extraneous | 불필요한
trailing | 후행
priority | 우선순위
slice | 슬라이스
space | 스페이스, 공백
comma | 콤마, 쉼표
semicolon | 세미콜론
colon | 콜론
list | 리스트, 목록
operation | 연산
operator | 연산자
operand | 피연산자
whitespace | 공백
index | 인덱스
annotation(s) | 어노테이션
compound statements | 복합문
folding | 폴딩

**Comment by Ohjiwoo-lab** [comment]
`#12 1차 번역 완료 ` 커밋에 2차 검토 사항 적어놓았습니다! 확인해주세요!
@Sumin0916

**Comment by zerosheepmoo** [comment]
@Ohjiwoo-lab
제가 1차 검토담당자는 아니기에 컨펌을 해드릴 수는 없겠지만...의견은 달아드렸습니다 :)

**Comment by Ohjiwoo-lab** [comment]
- 제가 검토를 진행한 부분이 Sumin0916 님이 진행한 것과 별개의 부분이 많아 이 글의 번역을 담당하신 zerosheepmoo 의 의견으로 2차 검토를 완료하였습니다.
- 혹시 수정하고 싶은 사항이 있으시다면 3차 검토에서 의견을 내주시면 감사하겠습니다!

**Comment by hajun-myoung** [comment]
3차 검토 코멘트 모두 달았습니다. *106번 줄* 외에는 모두 괜찮아 보입니다.
@Sumin0916 님 의견 있으시면 추가해주시기 바랍니다!

**Comment by Sumin0916** [comment]
2차, 3차 제안들 모두 읽어보았습니다!
딱히 더 수정할 부분이 없어 보이네요 3차 검토 내용 커밋 하셔도 될 것 같습니다!

**Comment by hajun-myoung** [comment]
추가 제안 없으시면 모두 동의 후에 클로즈 하겠습니다!
