### ISSUE TITLE
[안내] github action 을 이용한 자동 배포

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/pep8-in-korean#14]
## 계획

- docker 와 shell 로 구성하려 했지만..[다른 사람이 많든 좋은 액션을 찾음!](https://github.com/marketplace/actions/deploy-to-github-pages)

## 내용

- 현재 vuepress 로 static 사이트를 generate 할 수 있게끔 환경은 구성되어 있습니다.
- 문제는 배포 / 공개할 때 인데요. 본래 push 와 동시에 github page 에 배포할 수 있도록 구성할 예정이었으나 다음의 사항이 걸렸습니다.
    - 번역 문서를 수정한 후 웹페이지가 오류가 없이 배포가 되야함.
    - 이를 위해선 같이 collaborator 분들이 테스트(확인)을 잘해야 함.
    - 문제는 아직 이를 하는 연습이 충분하지 못한듯 보임.
- 그래서 이슈를 별도로 생성하고 각자 테스트화면을 띄워놓고 작업을 할 수 있는지 확인할 예정입니다.
    - 우선, 현재 프로젝트에 기여 중이신 @Sumin0916 , @Ohjiwoo-lab 이 이 이슈에 코멘트로 스크린샷을 첨부하고, 이를 확인한 후 깃허브 액션 환경을 구성할 예정입니다.
    - 당연히 나머지 분들도 차근차근 찍어주셔야 합니다.
    - 각자 `/docguide/contribute.md`를 참조하신 뒤 `npm run dev` 까지의 과정을 통해  `localhost:8080`에 테스트 환경을 구성해주세요. 그후 스크린샷을 찍어주세요. 

### 예시

> 터미널에 해당하는 부분만 스크린샷으로 첨부하셔도 상관없습니다.

<img width="1434" alt="Screenshot 2021-03-22 at 02 03 37" src="https://user-images.githubusercontent.com/52529894/111913795-d65a8380-8ab2-11eb-9288-65170f5e0374.png">

**Comment by Sumin0916** [comment]
![첨부](https://user-images.githubusercontent.com/72787222/111920141-b9cd4400-8ad0-11eb-8035-984e4e991a98.png)
- 실행 확인 되었습니다!

**Comment by Ohjiwoo-lab** [comment]
![image](https://user-images.githubusercontent.com/74577768/111987501-a4006300-8b52-11eb-9f79-a410768d5fd8.png)

- 실행확인 하였습니다!!

**Comment by susie-Choi** [comment]
![image](https://user-images.githubusercontent.com/38692338/112012651-b8515980-8b6c-11eb-8747-fa1f838d4347.png)
+ 실행 확인 하였습니다.

**Comment by zerosheepmoo** [comment]
## 결과

[깃허브페이지](https://zerosheepmoo.github.io/pep8-in-korean/)

다른 분들도 꼭 스크린샷 찍어서 여기 이슈에 코멘트로 달아주세요! 그후 클로즈 할 것 입니다. 👍

**Comment by zerosheepmoo** [comment]
- @xodnr8925 님은 모바일로 작업하셨기에 dev 환경을 실행할 수가 없음.
- 나머지 인원은 프로젝트 참여가 불확실하거나 참여를 안할 예정
- 따라서 해당 이슈 완료
