### ISSUE TITLE
PEP8 번역 - When to use trailing commas

### ISSUE THREAD

**Issue by Sumin0916** [zerosheepmoo/pep8-in-korean#16]
# 참여자
- 번역: @Sumin0916 
- 검토: 
  - 1차 : @zerosheepmoo 
  - 2차 : @hajun-myoung 
  - 3차: @zerosheepmoo

**Comment by zerosheepmoo** [comment]
# 단어 추출 목록

단어 | 뜻
-- | --
mandatory | 필수(사항)
element | 요소, 원소
redundant | 반복(하는, 적인)
semantics | 시맨틱, 의미론(적), 의미를 갖는
import | 가져오기
pattern | 패턴

**Comment by hajun-myoung** [comment]
@zerosheepmoo 2차 검토 완료했으니 확인 부탁드립니다ㅎㅎ
크게 수정할 만한 부분은 보이지 않네요. 사소한 것 몇 개만 제안했습니다 :)

**Comment by zerosheepmoo** [comment]
@hajun-myoung 확인하였습니다. 그대로 해주셔도 좋을 것 같습니다.

**Comment by zerosheepmoo** [comment]
# 3차 검토 내역

> 일반적으로 후행 쉼표[1]는 선택사항이다.
> 하지만, 한 개의 요소만을 갖고 있는 튜플을 만들 때는 필수사항이다.
> 튜플임을 명확히 하기 위해 (논리적으로는 중복이지만) 괄호로 둘러싸는 것을 권장한다.
> (그리고 Python 2 의 print 문에서는 개별적인 의미를 갖는다(semantic)).

- 가독성을 위해 문장을 분리하였습니다.
- `다음과 같은 상황`이라는 표현은 우선 영어식 표현이므로 자제하는 것이 좋고, 원문 글에는 `단일 요소의 튜플을 만들 때`로부터 이어지는(가 생략된) 문장이므로, 불필요하게 예시에 의존하는 듯이 번역할 필요는 없습니다. 단지 무엇을 명확히함을 명시하면 가독성이 향상된다고 판단하였습니다.
- 지나친 영어식 어순으로 인해 문단의 통일성이 떨어져 보입니다. 통일성 향상을 위해 번역 순서에는 어긋나지만, 괄호부분을 문단 뒤로 보냈습니다.
- print 문에서는 후행 쉼표가 의미를 갖는다는 표현은 마치 본래에도 후행쉼표가 아무런 의미가 없는 듯이 보이므로, 의역이지만 `개별적인`을 추가하였습니다.

> 후행 쉼표가 중복인 경우, 버전 관리 시스템을 사용할 때 도움이 된다.
> 예를 들면, 값, 아규먼트, 가져오기(import)한 아이템들의 리스트가 시간이 지남에 따라 확장될 가능성이 있을 때 유용하다.
> 각 값(또는 아규먼트나 가져오기한 아이템)을 각 줄에 배치하고,
> 항상 후행 쉼표를 추가한 다음, 마지막 줄에 괄호로 닫는 패턴을 사용한다. 
> 닫힌 구분 문자와 후행 쉼표가 같은 줄에 있는 것은 합리적이지 못하다.
> (단, 위처럼 싱글톤 튜플의 경우는 제외)

- 가독성 향상을 위해 문장을 분리하였습니다.
- 사실 `패턴은 ~ 하다`의 문장이지만 지나친 영어식 표현이므로 `~을 사용하자`로 번역되었으나, 명령문보다는 평어체에 가까우므로 사용한다로 바꾸었습니다.
- 각 줄에 후행 쉼표를 추가한 다음, 그 다음줄에서 괄호로 닫으므로, 마지막 줄이라 의역하는 것이 가독성을 높입니다.
- 닫는 => 닫힌, 단일형 => 싱글톤 == 단어목록 표에 의함.
- 지나친 접속어로 가독성이 떨어지는 듯하여 `닫힌 구분 문자~` 문장에서 접속어를 삭제하였습니다.

모두의 동의하에 클로즈하겠습니다.

**Comment by hajun-myoung** [comment]
`닫힌 구분 문자~` 문장에서의 접속어는 남아있는 편이 낫지 않을까요? 혹시 `물론` 정도의 접속어는 어떨까요?
> 물론, 닫힌 구분 문자와 후행 쉼표가 같은 줄에 있는 것은 합리적이지 못하다.

나머지 검토하신 내용들은 모두 동의합니다!

**Comment by zerosheepmoo** [comment]
`하지만` 은 몇번이고 읽어봤을 때 적절치 못한 느낌을 받았습니다.
`물론` 도 구어체의 느낌이 들어 꺼려집니다만...
does not make sense 의 원문 번역을 포기하는 편이 자연스럽겠습니다.

> 그리고 닫힌 구분 문자와 후행 쉼표는 같은 줄에 두지 않는다.

**Comment by hajun-myoung** [comment]
`그리고` 괜찮네요. 동의합니다!

**Comment by Sumin0916** [comment]
`그리고` 괜찮은 것 같습니다!
3차 검토 내용 동의합니다!
