### ISSUE TITLE
PEP8 번역 - Comments

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/pep8-in-korean#19]
## 참여자

- 번역: @zerosheepmoo 
- 검토
  - 1차: @Sumin0916
  - 2차: @hajun-myoung 
  - 3차: @zerosheepmoo

**Comment by zerosheepmoo** [comment]
sparingly 를 `적게` 보단 `꼭 필요한 경우에`로 번역해야 의미전달이 더욱 좋겠습니다.
2차 검토하시는 분께서 적용해주세요!

**Comment by zerosheepmoo** [comment]
# 단어 추출 목록
단어| 뜻
-- | --
comment | 주석
up-to-date | 최신 (상태)
identifier | 식별자
block comments | 블록 주석
paragraph | 단락
period | 마침표
sparingly | 꼭 필요한 경우에

**Comment by hajun-myoung** [comment]
@Sumin0916 2차 검토 코멘트 모두 달았습니다. 확인 부탁드려요!
@zerosheepmoo 
- line 17-18, 처음 번역하신 문장 수정을 제안했습니다. 검토 부탁드려요.
- line 35, 말씀하신 `sparingly` 수정 제안도 확인 부탁드려요.

**Comment by zerosheepmoo** [comment]
# 3차 검토 내역

> 블록 주석 안의 단락들은 `#` 한 개를 포함한 줄로 구분된다.

- 번역이 잘못되었습니다.

나머지는 깔끔한 번역입니다. 모두의 동의하에 클로즈하겠습니다.
