### ISSUE TITLE
PEP8 번역 - Introduction

### ISSUE THREAD

**Issue by Sumin0916** [zerosheepmoo/pep8-in-korean#2]
## 참여자
- 번역: @Sumin0916 
- 검토
  - 1차: @zerosheepmoo
  - 2차: @Ohjiwoo-lab 
  - 3차: @zerosheepmoo

**Comment by zerosheepmoo** [comment]
## 검토

- [번역 철학](https://github.com/zerosheepmoo/pep8-in-korean/blob/master/docguide/trans-philosophy.md) 문서에 명시한 바에 따르면 기본적으로 경어체는 자제하게 되어있습니다. 혹여나 경어체로 통일하는 것이 낫다 생각하시면 새로운 이슈를 열어 이야기를 나누어보아요!
- commit 을 할 때 commit 하나 당 이슈 하나에 연결 되어야합니다. 좀 번거로우시더라도 다른 collaborator 가 작업한 것을 볼 때 불편할 수 있어요. push 를 여러 번 할 필요는 없지만 커밋은 2, 3, 5 에 대한 것을 따로 했으면 좋겠습니다. 우선 이미한 커밋인데다가 revert 나 reset 하기엔 미미한 수준이라...다음부터는 이 원칙을 지켜보도록 해요 :)
- 번역에 대한 코멘트는 커밋에 싱글코멘트로 달아보도록 할게요!

**Comment by Sumin0916** [comment]
넵 다음부터는 커밋을 이슈마다 나누어 올리도록 하겠습니다!

**Comment by Sumin0916** [comment]
커밋, 이슈 답글 확인하여 수정하였습니다!

**Comment by Sumin0916** [comment]
> ## 검토
> * [번역 철학](https://github.com/zerosheepmoo/pep8-in-korean/blob/master/docguide/trans-philosophy.md) 문서에 명시한 바에 따르면 기본적으로 경어체는 자제하게 되어있습니다. 혹여나 경어체로 통일하는 것이 낫다 생각하시면 새로운 이슈를 열어 이야기를 나누어보아요!

상대방을 높이는 부드럽고 차분한 경어체 보다 간결하고 팩트를 명료하게 전달하는 평어체가 더 읽기 좋은 것 같네요!

**Comment by zerosheepmoo** [comment]
## 2차 리뷰어 분께...

- "문서 문자화 컨벤션"으로 번역되어 있는 부분을 "독스트링 컨벤션"으로 수정해주세요. 기본적으로 documentation strings 를 문서화 문자열로 번역하고, docstring 은 독스트링이라 번역하기로 정해져있습니다. 이견이 있는 경우 용어토론 스레드를 생성해주세요.

**Comment by Ohjiwoo-lab** [comment]
# 2차 검토
2차 검토 comment 남겨두었습니다! 확인해주세요!

**Comment by zerosheepmoo** [comment]
@Ohjiwoo-lab 체크하였습니다. 확인해주세요.

**Comment by zerosheepmoo** [comment]
# 3차 검토 사항

- 가독성 향상을 위해 중복되는 의미의 문장을 지움

**Comment by zerosheepmoo** [comment]
# 단어 추출 목록

- companion: 지침서
- guideline: 가이드라인
- style: 스타일
- code: 코드
- convention: 컨벤션
- conflict: 충돌
- docstring: 독스트링

**Comment by zerosheepmoo** [comment]
해당 이슈는 모두의 동의하에 클로즈합니다.

**Comment by Sumin0916** [comment]
동의합니다!

**Comment by Ohjiwoo-lab** [comment]
저도 동의합니다 :)
