### ISSUE TITLE
PEP8 번역 - Naming Conventions - Descriptive:Naming Styles

### ISSUE THREAD

**Issue by susie-Choi** [zerosheepmoo/pep8-in-korean#20]
# 참여자
- 번역: @susie-Choi 
- 검토: @zerosheepmoo

**Comment by zerosheepmoo** [comment]
## 질문 

동일한 이름의 커밋이 3개로 나누어져있는데요. 특별한 이유가 있을까요???

**Comment by susie-Choi** [comment]
> ## 질문
> 동일한 이름의 커밋이 3개로 나누어져있는데요. 특별한 이유가 있을까요???

## 대답
commit 할 때 #issue number 를 붙였는데 Github상에서 표시가 안되서 다시 커밋하였습니다!

**Comment by zerosheepmoo** [comment]
## 제안

아하 그렇군요. 
혹시 괜찮으시다면, 깔끔한 이력관리를 위해 `git reset --mixed HEAD~3` 로 돌리신 후 `git push -f origin master` 해주실 수 있나요??
아직 pull 받으신 분들이 없을 것 같아, 괜찮을 것 같은데요...어떠신가요?

**Comment by susie-Choi** [comment]
> ## 제안
> 아하 그렇군요.
> 혹시 괜찮으시다면, 깔끔한 이력관리를 위해 `git reset --mixed HEAD~3` 로 돌리신 후 `git push -f origin master` 해주실 수 있나요??
> 아직 pull 받으신 분들이 없을 것 같아, 괜찮을 것 같은데요...어떠신가요?

## 대답
흠 commit reset 을 하고 싶어도
vuepress 에러 + 현재 커밋처럼 소소한 에러들로 인해 로컬 레포지토리를 자꾸 갈아엎다보니 현재 clone --mirror 된 상태라 못한다고 뜨는군요..

**Comment by zerosheepmoo** [comment]
- 해당 명령을 했을경우 발생하는 에러 메시지를 보내주세요. Pull 하셨을 때 오류나는 것은 아니시지요?
- 혹 fork 된 레포지토리로 작업하고 계신지요. Pull request 단위를 쓸일이 없을것걑아 git clone 을 권장했습니다만...작업방식은 자유므로 상관은 없을듯합니다.
- 정말 죄송합니다.. 로컬 레포지토리를 갈아 엎는 번거로움을 드렸군요ㅠㅠ 많이 번거로우시다면 이력 수정은 안하셔도 괜찮습니다.

**Comment by susie-Choi** [comment]
- 네 pull 오류는 아니고 git reset --mixed Head~3 시 fatal: mixed reset is not allowed in a bare repository 라는 오류가 발생합니다.
- fork된 레포지토리는 commit 을 최소화하기 위하여 제가 따로 작업하고 있는 장소입니다. fork 레포지토리에서 먼저 commit을 해 보고 의도한 대로 정상 출력되는지 확인 뒤 이곳에 올리고 있습니다.
- 이전에 이력 관리까지는 신경쓰질 않다 보니 이런 문제가 생기는군요.. 저야말로 신경쓰시게 해서 죄송합니다.

**Comment by zerosheepmoo** [comment]
그렇군요. 본래 포크된 레포지토리는 리셋을 못하게 되어있어서 그렇긴 합니다. 해당 메시지는 그를 나타내는 것이고요.

이럴때는 레포지토리를 클론하여 작업하시거나 제가 정리후 다시 환경을 구성하시는 방법이있습니다만...
참고만 해주세요 :)

**Comment by zerosheepmoo** [comment]
## 1차 검토 내역

- 마크다운 스타일 가이드에 어긋난 형식 수정
- 가독성 향상을 위한 자잘한 언어선택 추가
- 역자주 표시

## 토론 

trailing 은 후행으로 번역하는 것이 일반적이나, leading 같은 경우, 가독성으로 인해 저는 `첫 글자`로 번역을 해왔는데요.
trailing 과 매칭되게 선행으로 번역하는 것이 좋을지 고민입니다.
2차 검토하시는 분이 의견 달아주세요 👍

**Comment by zerosheepmoo** [comment]
#39 로 통합
