### ISSUE TITLE
처음 참여하는 팀원들의 테스트를 위한 introduction page 만들기

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/pep8-in-korean#22]
> #17 의 일환

## 내용

- 처음 기여하는  팀원들을 위한 가이드 영상의 일환
- 간략한 자기소개, 다짐 등을 적은 페이지를 제작

`src/hello/` 디렉토리에 넣기

**Comment by zerosheepmoo** [comment]
영상 제작 후 닫을 것

**Comment by youngyangmoo** [comment]
영상제작이 오래걸리지만, 이는 이슈 #17 에서 관리하도록 하며, hello 를 만들었으므로 이슈관리를 위해 클로즈
