### ISSUE TITLE
Unable to checkout working tree 오류

### ISSUE THREAD

**Issue by Sumin0916** [zerosheepmoo/pep8-in-korean#27]
- `git clone`을 실행하는 중 오류가 발생하였습니다.
- 인터넷에서 오류명과 관련하여 해결방법을 찾아본 결과, 프로젝트 내에 있는 파일명 중 OS에 호환되지 않는 파일명이 원인이라는 [답변](https://stackoverflow.com/questions/61614004/cloning-succeded-but-checkout-failed-due-to-invalid-path-what-is-the-path-probl)을 찾게 되었습니다:(
- 아래 Error log를 보면 "descriptive: naming-styles.md"를 인식하지 못하는 것 같아서 이 파일명 정도만 수정을 해주시면 제가 다시 clone을 해보고 정상적이면 이슈를 종료해도 될 것 같습니다!
```
.
.
.
Resolving deltas:  96% (367/382)
Resolving deltas:  97% (371/382)
Resolving deltas:  98% (375/382)
Resolving deltas:  99% (379/382)
Resolving deltas: 100% (382/382)
Resolving deltas: 100% (382/382), done.
error: invalid path 'src/doc/descriptive: naming-styles.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
- 작업환경: Window10

**Comment by susie-Choi** [comment]
- 파일 이름 수정였습니다. clone 재시도 부탁드립니다.

**Comment by Sumin0916** [comment]
- 오류 해결되었습니다!
