### ISSUE TITLE
PEP8 번역 - Reference

### ISSUE THREAD

**Issue by Sumin0916** [zerosheepmoo/pep8-in-korean#3]
## 참여자

- 번역: @Sumin0916 
- 검토: @zerosheepmoo

**Comment by Sumin0916** [comment]
참조 6번에 straddling code가 마음에 걸립니다,,,,
"Tools that support this syntax should support it regardless of the Python version being checked. This is necessary in order to support code that **straddles** Python 2 and Python 3."
위 참고 문헌 straddling code 관련 부분 문장을 읽고 우선은 양립 가능 코드라고 적어보았습니다

**Comment by zerosheepmoo** [comment]
docguide 디렉토리는 문서 번역을 어떻게 하면 좋을지 안내하는 디렉토리가 되어야합니다.
후에 vuepress 환경을 세팅하면서 디렉토리가 옮겨지겠지만, 그 전에 markds 디렉토리로 이동하겠습니다.

**Comment by zerosheepmoo** [comment]
## 번역에 대한 답변

[해당 부분](https://www.python.org/dev/peps/pep-0008/#id13)을 저도 확인했습니다.

[옥스퍼드 영영사전](https://www.oxfordlearnersdictionaries.com/definition/english/straddle#straddle_sng_2)을 참고하면 두 군데 다 존재할 수 있는 으로 번역될 수 있는데요.
양립가능한 코드 라는 번역은 적절한 듯 합니다.
단지 원문이 어떤지 표기해주는 것도 괜찮은 듯합니다.

> Python 2.7 및 양립 가능 코드(straddling code)를 위한 문법 제안

## 마크다운 형식에 대한 검토

아직 마크다운 스타일 가이드를 명시하지 않았지만...구글의 마크다운 스타일 가이드랑 흡사하게 진행할 가능성이 높습니다.
우리 스타일 가이드가 아니더라도 일반적으로 마크다운 파일안에서 html 형식을 쓰는 것은 자제되어야 하는데요.
name 어트리뷰트를 사용하신 이유가 특별하지 않으시다면 다음으로 수정하는 것이 가독성에도 좋겠습니다.

### 수정 전
```md
<a name="ref_1">[1]</a>: PEP7,  C언어 스타일 가이드, van Rossum
```

### 수정 후
```md
[[1]](#ref_1): PEP7,  C언어 스타일 가이드, van Rossum 
```

**Comment by Sumin0916** [comment]
> docguide 디렉토리는 문서 번역을 어떻게 하면 좋을지 안내하는 디렉토리가 되어야합니다.
> 후에 vuepress 환경을 세팅하면서 디렉토리가 옮겨지겠지만, 그 전에 markds 디렉토리로 이동하겠습니다.

확인하였습니다!

**Comment by Sumin0916** [comment]
검토해주신 부분 확인하여 수정하였습니다
추후 각주를 작성할 때 참고하겠습니다!

**Comment by zerosheepmoo** [comment]
단지 지금 고민해야할 사항이 있는데요. 
어떻게 [1] 등의 각주를 반영할 것인가 인데...이는 규칙을 정해놓고 markdown 문서를 html 로 generate 할 때 바꿔줄 만한 형식을 정하든, 
아니면 다른 방법을 고민해보든 해야겠습니다.
좋은 생각있으면 언제든지 알려주세요! 이는 별도의 이슈로 관리하겠습니다.

**Comment by zerosheepmoo** [comment]
@Sumin0916 

위에 reference 된 이슈로 가셔서 extended markdown syntax 에 있는 footnote 구문 참조하신 후 이 이슈와 관련된 번역에 사용하시길 바랍니다.

그 후 푸쉬한뒤 지금 이슈를 클로즈하셔도 좋을 것 같습니다 :)

**Comment by Sumin0916** [comment]
넵 #3 클로즈 하겠습니다~!

**Comment by zerosheepmoo** [comment]
#10 에 따라 2명의 리뷰어가 추가로 필요하므로 이슈를 재오픈합니다.

**Comment by zerosheepmoo** [comment]
## 안내

- footnote 사용에 따라 각 문서페이지마다 각주를 명시하는 것이 맞기 때문에 Reference 번역은 각주가 달려잇는 부분 번역하시는 분이 같이 번역하시길 바랍니다.
- 지금 이 항목에서 번역된 항목을 참고하셔서 적어주세요.

**Comment by zerosheepmoo** [comment]
현재 전문의 1차번역이 완료되었으므로 각주가 있는 섹션의 번역담당자와 리뷰어들이 이 이슈에 대한 역할을 부여받게 됩니다.
