### ISSUE TITLE
pep8 번역 Code-layout - Tabs or Spaces?

### ISSUE THREAD

**Issue by Ohjiwoo-lab** [zerosheepmoo/pep8-in-korean#30]
# 참여자
- 번역: @Ohjiwoo-lab 
- 검토
  - 1차: @zerosheepmoo
  - 2차: @Sumin0916 
  - 3차: @zerosheepmoo

**Comment by zerosheepmoo** [comment]
@Ohjiwoo-lab 1차 검토하였습니다. 확인해주세요.

**Comment by Ohjiwoo-lab** [comment]
@zerosheepmoo 확인했습니다! 좋은 것 같습니다 수정해주세요!

**Comment by Sumin0916** [comment]
- 2차 검토 완료하였습니다. 수정 제안한 부분 확인 부탁드립니다!

**Comment by zerosheepmoo** [comment]
@Sumin0916 답변 달아드렸습니다. Pull 하신 후 수정하여 반영하시면 될 것 같습니다.

**Comment by zerosheepmoo** [comment]
## 단어 추출 목록
단어 | 뜻
-- | --
command line interpreter | 명령 줄 인터프리터
option | 옵션, 선택 사항
tab | 탭
error | 에러, 오류
warning | 경고

**Comment by Sumin0916** [comment]
동의합니다!

단어 추출 목록에서 `명령어 인터프리터`를 `명령 줄 인터프리터`로 바꾸지 않아도 될까요?

**Comment by zerosheepmoo** [comment]
@Sumin0916  정정하였습니다.

**Comment by zerosheepmoo** [comment]
해당 이슈는 모두의 동의하에 클로즈합니다.

**Comment by Ohjiwoo-lab** [comment]
동의합니다!!
