### ISSUE TITLE
Pep8 번역 - Code Lay-out - Maximum Line Length

### ISSUE THREAD

**Issue by Ohjiwoo-lab** [zerosheepmoo/pep8-in-korean#37]
# 참여자
- 번역 : @Ohjiwoo-lab 
- 검토
  - 1차: @zerosheepmoo 
  - 2차: @Sumin0916 
  - 3차: @zerosheepmoo

**Comment by zerosheepmoo** [comment]
검토 제안하였습니다. 확인해주세요!

**Comment by Ohjiwoo-lab** [comment]
표현이 더 자연스러워 진 것 같군요! 좋은 것 같습니다!!

**Comment by Sumin0916** [comment]
- 2차 검토 완료하였습니다. 제안 확인 부탁드립니다!

**Comment by zerosheepmoo** [comment]
# 단어 목록 추출
단어 | 뜻
-- | --
max line length | 한 줄의 최대 길이
character | 문자
open side by side | 창 분할
tool | 툴
marker | 표시, 마커
glyph | 글리프
column | 열
dynamic | 다이나믹, 동적
exclusively | 배타적으로
primarily | 우선적으로
conservative | 보수적
expression(s) | 표현
line continuation | 줄 잇기
line break | 줄 바꿈

**Comment by zerosheepmoo** [comment]
# 3차 검토 내역

- 띄어쓰기를 했습니다
- 문장을 줄였습니다.
- 특히 require 같은 경우 요구한다 보다는 ~이 필수적이다에 의미가 가까우므로 그냥 stdlib 가 그렇다고 번역하는 것이 더욱 적절합니다.
- 이러한 경우의 가 가독성을 해쳐 지웠습니다.

**Comment by zerosheepmoo** [comment]
해당 이슈는 모두의 동의하에 클로즈합니다.

**Comment by Ohjiwoo-lab** [comment]
가독성이 많이 좋아진 것 같습니다 :) 동의합니다~

**Comment by Sumin0916** [comment]
저도 좋은 것 같습니다! 동의합니다!
