### ISSUE TITLE
[notice] 작업 지연에 따른 안내

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/pep8-in-korean#38]
## 안내

마지막 커밋, 이슈가 올라오고 나서부터 약 한 달이 지났습니다.
python 스타일가이드는 여러 개인 블로그에서도 번역할 만큼 그 내용이 방대하지는 않기 때문에,
더 이상 시간을 지체하는 것은 프로젝트기여에 효과적이지 못하다고 판단하였습니다.
또, 자칫 [abandoned](https://www.repostatus.org/) 상태로 전화될 가능성이 있다고 보았습니다.

따라서 **5월 내로** 이 프로젝트를 **종료**할 계획입니다.

## 목표

~~- `2021-05-08~15`: 미 부여된 섹션 1차번역 완료~~ `완료`
~~- `2021-05-16`: 부여된 섹션 중 번역담당자가 15일 까지 마치지 않은 섹션을 번역.~~ `완료`
- `2021-05-23`: 전문 2차번역 및 검토완료
- `2021-05-30`: 전문 3차번역 및 검토완료
- `2021-05-31`: 마지막 배포

## 위의 계획대로 이루어지지 않았을 경우

- 잠재적으로 보장되지 않은 번역 섹션임을 표기하게 됩니다.

## 더 이상 프로젝트에 기여하기가 어렵다고 판단한 경우

- 아직 한 번도 기여를 안하신 팀원은 slack, kakaotalk 상관없이 저에게 연락을 주세요.
  - 연락 후 탈퇴의사를 표명하시면 콜라보레이터에서 제외시켜드립니다.
- 한 번이라도 기여하신 분은 기여자로 분류되며, 프로젝트 레포지토리 탈퇴 필요 없이 slack 에서 의사표현 후 활동 중단하시면 됩니다.

## 번역 외 기능

- 전문 1차 번역 완료 후 적용합니다.

**Comment by zerosheepmoo** [comment]
## 미참여 인원에 대하여

> 자신이 암시적 미참여 인원인 경우 `~5/23` 까지 @zerosheepmoo 에게 연락바람.

- 현재 명시적 미참여 인원은 다음과 같다.
  - `blue980511`: 컨트리뷰터에서 제외
  - `wooseong-dev`: 컨트리뷰터에서 제외
  - `susie-Choi`: `프로젝트 완료`
  - `xodnr8925`: `프로젝트 완료`

## 참여인원은...

- 현재 활동 인원은 다음과 같다.
  - `Sumin0916` 
  - `Ohjiwoo-lab`
  - `zerosheepmoo`

## 그래서

- 현재 #10 에 따라 1명의 번역담당자가 번역을 하고 3명의 리뷰어가 approval 을 내주어야 하나의 섹션의 번역이 완료된다.
- 현재 참여 최대 인원이 3명이므로 이 상태는 완료될 수 없다.
- 따라서 이에 대한 논의가 필요하다.
- 새로운 인원을 모집할 의향이 있으니, @Sumin0916 님과 @Ohjiwoo-lab 님이 모든 항목을 검토해주신다면 3명 approval 정책을 유지하겠습니다.

**Comment by Sumin0916** [comment]
## 의견
- 저는 계속 검토를 할 의향이 있습니다,,!
- 우선 3인 approval 방식을 유지해보고 3차 검토를 제외한 작업이 거의 완료 되었을 때쯤, 다시 생각해 보는 것도 좋아 보입니다.
- 추가 의견으론 3차 검토를 기존 사람이 추가로 할 수 있도록 새로운 검토 기준을 만들어 보는 것도 있을 것 같네요,, (ex, 3차 검토는 맞춤법 검사와 이 문단이 전체 글 흐름에 맞는지를 검사합니다....등등 나름 객관적인 규칙을 적용해 보는 것 입니다.)

**Comment by Ohjiwoo-lab** [comment]
## 의견
- 제가 시간 상 모든 항목에 대해 검토를 할 수는 없을 지도 모르지만 최대한 하도록 노력해보겠습니다!
- 이러한 점을 볼 때 저도 한번 검토를 했던 분이 또 다시 검토를 할 수 있도록 하는 방식이 효율적으로 보입니다! 현재 인원으로 3차 검토를 수행하기에 다소 무리가 있을 것으로 보이긴 합니다.
- Sumin0916 님 의견에 동의합니다! 3차 검토는 1, 2차 검토처럼 세세한 사항들을 모두 확인하는 것이 아니라 큰 틀에서 문맥이 자연스러운 지를 판단하는 식으로 하면 시간도 여유로울 것 같습니다.

**Comment by zerosheepmoo** [comment]
해당 이슈 전달 사항의 공지가 완료되었으며, 앞으로의 일정은 유동적으로 관리를 하므로 클로즈합니다.
