### ISSUE TITLE
PEP8 번역 - Copyright

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/pep8-in-korean#40]
# 참여자
- 번역: @zerosheepmoo 
- 검토
  - 1차: @Sumin0916
  - 2차: @Ohjiwoo-lab 
  - 3차: @zerosheepmoo

**Comment by Sumin0916** [comment]
- 1차 검토 완료하였습니다 확인 부탁드립니다!

**Comment by zerosheepmoo** [comment]
@Sumin0916 코멘트 남겨드렸습니다 :) 읽어보시고 반영해주시면 될 거 같습니다.

**Comment by zerosheepmoo** [comment]
# 단어 추출 목록

- public: 공개, 퍼블릭
- domain: 도메인
- place: 배치하다, 위치하다.

**Comment by Ohjiwoo-lab** [comment]
2차 검토하였습니다!확인해주세요!

**Comment by zerosheepmoo** [comment]
# 3차 검토 내역

특별히 수정할 것들이 없습니다.

모든 분이 동의하시면 클로즈하겠습니다.

**Comment by Ohjiwoo-lab** [comment]
동의합니다 :)

**Comment by Sumin0916** [comment]
동의합니다!
