### ISSUE TITLE
PEP8 번역 - Code Lay-out 나머지 

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/pep8-in-korean#41]
## 참여자
- 번역 : @zerosheepmoo
- 검토
  - 1차: @Ohjiwoo-lab 
  - 2차: @hajun-myoung 
  - 3차: @zerosheepmoo 

## 목록

- Should a Line Break Before or After a Binary Operator?
- Blank Lines
- Source File Encoding
- Imports
- Module Level Dunder Names

**Comment by zerosheepmoo** [comment]
이슈는 분리하되, 파일은 하나로 합치는 작업을 수행함. (차후 vuepress 업데이트 적용을 위해)

**Comment by Ohjiwoo-lab** [comment]
코멘트 모두 달았습니다 :) 확인해주세요!

**Comment by zerosheepmoo** [comment]
@Ohjiwoo-lab 모든 코멘트에 대한 답변을 완료하였습니다. 정말 고생많으셨습니다 👍

**Comment by zerosheepmoo** [comment]
# 단어 추출 목록

단어 | 뜻
-- | --
binary operator | 이항 연산자
extra | 추가
publisher | 퍼블리셔
formula | 공식
blank | 공백
dummy | 더미
set | 집합
group | 모음
separator | 구분자
feed | 피드
form | 형식, 폼, 양식
viewer | 뷰어
distribution | 배포
declaration | 선언
default | 초기값, 디폴트
author | 작성자
case | 경우, 케이스
test | 테스트
policy | 정책
absolute | 절대적인, 절대경로의
relative | 상대적인, 상대경로의
config | 구성하다
alternative | 대안
layout | 레이아웃
spell(ing) | 철자, 글자
clash | 충돌하다
automation | 자동화
republish | 다시 게시하다
publish | 게시하다
definition | 정의
overwritten | 덮어 쓴
apply | 적용하다
level | 레벨
dunder | 던더
mandates | 명령
command | 명령(하다)
hanging indent | 내어쓰기
indent | 들여쓰기

</google-sheets-html-origin>

**Comment by Ohjiwoo-lab** [comment]
## 2차 검토자분께
~~`들여쓰기` 부분에 `올바른 예`라 되어 있는 것을 `옳은 예`로 수정 부탁드립니다!~~
제가 다른 파일까지 일괄적으로 변경하도록 하겠습니다 :)

**Comment by hajun-myoung** [comment]
@Ohjiwoo-lab 2차 검토 코멘트 모두 달았습니다. 확인 부탁드려요 😄

**Comment by Ohjiwoo-lab** [comment]
동의합니다 :) 수정해주세요!!

**Comment by zerosheepmoo** [comment]
# 3차 검토내역

> 두 가지 이유로 가독성을 해칠 수 있다.
> 첫째, 연산자들이 화면의 여러 열(columns)에 흩어지는 경향이 있다.
> 둘째, 각 연산자가 대응되는 피연산자로부터 떨어져 이전 줄로 이동한다.

- 두 가지 이유가 있다 뒤의 문장의 응집성을 높이기 위해 `첫째`, `둘째`를 추가하여 다른 구조로 번역하였습니다.
- 이 경우 조사가 미묘하게 달라져 `옮기다`라는 표현 보다는 `이동한다`가 적절해졌습니다.

> 공백 줄은 관련된 one-liner[^4] 의 모음 사이에서 생략될 수 있다.
> ...
> 함수 내 공백 줄은 논리적인 섹션을 구분할 때 적절하게 사용하자.

- group 은 모음으로
- `논리적인 섹션을 나타내기 위해 함수 내에서 공백 줄을 꼭 필요한 경우에만 사용하자.` 가독성이 떨어집니다.
- sparingly 를 꼭 필요한 경우에만으로 하는 게 원어의 느낌을 더 살리는 것은 맞으나, 이 문장에 한 해서는 다른 뜻으로 번역하겠습니다.
- indicate 를 구분하기로 의역했습니다.

> 많은 툴들이 이 문자를 페이지 구분자로 취급하므로,
> 이를 파일 내 서로 관련된 섹션들의 페이지를 분리하기 위해 사용할 수 있다.
> 단, 몇 에디터와 웹 기반 코드 뷰어에서는 컨트롤 + L 이 폼 피드로 인식되지 않을 수 있다는 점을 주의하자.
> 그 코드 뷰어는 그 위치에 다른 글리프를 보여줄 것이다.

- 문장이 너무 짧아 어색해지므로 접속사를 없애고 복합문으로 고쳤습니다.
- `단` 을 붙여 문장 간 응집성을 높였습니다.
- 뒷 문장의 주어가 생략되어 가독성이 떨어지므로 `그 코드 뷰어는`을 삽입했습니다.

> 코어 Python 배포 코드는 항상 UTF-8을 사용해야 한다.
> ...
> 인코딩 선언부(declaration)를 포함하면 안된다.
> ...
> (많은 경우에, 약어나 기술적인 용어만을 영어가 아니어도 사용한다.)
> ...
> 전자(transliteration)[^5]를 제공해야 한다.

- 불필요한 조사를 없앴습니다.
- 파일 내에 소유한 것이므로 `선언부를 포함한다`로 의역하여 가독성을 높였습니다.
- 피동 표현을 없앴습니다.
- 조사를 고쳤습니다.

> - 가져오기는 항상 파일의 맨 위에 놓여져 있다.
>   세세하게는 모듈 주석과 독스트링 바로 다음에, 모듈 전역과 상수 바로 전에 놓여져 있다.

- 말이 길어졌지만 표현을 좀 더 매끄럽게 바꿨습니다.

> - 클래스를 갖고 있는 모듈에서 클래스를 가져올 때, 다음과 같이 작성하는 것은 괜찮다.
>   만약 이 철자가 로컬 이름과 충돌이 발생하면, 명시적으로 작성하자.

- 철자를 바꾸다는 본래의 뜻을 왜곡하는 경향이 있으므로 `작성하다`로 의역합니다. spell 자체가 동사로 사용된 경우라 직역에서는 마땅한 대안이 없네요.

> 이들은 네임스페이스 안에서 보여지는 이름들을 불분명하게 만들고,
> 독자를 혼란시키며 여러 자동화 툴들에 혼선을 준다.
> 단, 와일드 카드 가져오기를 사용할 수 있는 사례가 하나 있다.
> 공개 API의 일부로 내부 인터페이스를 다시 게시(republishing)하는 경우다.
> (예를 들어, 선택적 가속기 모듈(optional accelerator module) 내 로부터 온 정의로,
> 인터페이스의 순수 Python 구현을 덮어 쓰는데,
> ...
> [퍼블릭 그리고 내부 인터페이스에 관한 가이드라인](./naming-conventions.md#퍼블릭-그리고-내부-인터페이스)
  은 계속 적용된다.

- 우리나라의 표현에서는 독자와 자동화 툴들에 대한 표현이 달라야 자연스럽습니다.
- 가독성 향상을 위해 문장을 나누었습니다.
- 방어적인 등의 영어식 표현은 삭제하고 의역하였습니다.
- `로부터의 정의`는 모듈 내에 선언되어있는 definitoin 인지 모듈 자체에 대한 정의를 이야기하는 것인지 중의적입니다. 이를 피하기 위해 표현을 수정하였습니다.
- 단어표에 따라 지침서가 아닌 가이드라인으로 번역하였습니다.
- `아래의`는 원문 문서와는 다르게 다른 페이지에 위치해 있으므로 삭제하였습니다.

> 모듈 레벨의 "던더들"은 모듈의 독스트링 다음, 모든 가져오기 구문 전에 있어야 한다.

- `위치해야 한다` 가 일본식 표현인 줄은 몰랐습니다. 분명이 영어를 직역한 것일텐데...자제해야한다면 그리해야겠죠?
- 제가 전 문서에 위치하다는 표현을 일괄적으로 수정하겠습니다.
- [국립 국어원 위치하다](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=134895)

모두의 동의하에 클로즈하겠습니다.

**Comment by Sumin0916** [comment]
> 위치해야 한다 가 일본식 표현인 줄은 몰랐습니다. 분명이 영어를 직역한 것일텐데...자제해야한다면 그리해야겠죠?

저도 이 부분은 몰랐네요,,!
수정사항 확인하였습니다 동의합니다!

**Comment by hajun-myoung** [comment]
그러게요, `위치한다` 가 일본식 표현이라니, 놀랍네요 O_O

다음 한 부분 제외하고 이견 없습니다!

## 제안

> (예를 들어, 선택적 가속기 모듈(optional accelerator module) 내 로부터 온 정의로,

- `내로부터`로 붙여써야 할 것 같아요.

  > (예를 들어, 선택적 가속기 모듈(optional accelerator module) 내로부터 온 정의로,
