### ISSUE TITLE
PEP8 번역 - Programming recommendations

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/pep8-in-korean#42]
### programming recommendations
- 번역 : @zerosheepmoo
- 검토
  -  1차: @Sumin0916 
  -  2차: @hajun-myoung 
  -  3차: @Sumin0916 
  
### variable, function annotations

- 번역: @xodnr8925 
- 검토
  - 1차: @zerosheepmoo 
  - 2차: @hajun-myoung 
  - 3차: @Sumin0916 
 
## 추가

~~- @xodnr8925 님이 번역한 #36 과 #26 를 합침~~
- 이슈관리를 위해 위의 이슈를 이곳으로 통합
- 레이블 표시는 다음에 내용에 대응된다.
  - `검토요청 1차`: programming recommendations
  - `검토요청 2차`: #36, #26
- 둘의 단계가 같아졌을 때 `검토완료`를 표기하자

**Comment by Sumin0916** [comment]
programming recommendations 1차 검토 완료하였습니다!

**Comment by zerosheepmoo** [comment]
# 단어 추출 목록
단어 | 뜻
-- | --
efficient | 효율적인
concatnation | 연결
string | 문자열
rely on | 의존하다
linear time | 선형 시간
dependency | 의존성
singleton | 싱글톤
context | 문맥, 컨텍스트
equality | 등호, 동등성
rich | 리치
decorator | 데코레이터
assume | 가정하다, 간주하다
reflexivity | 반사성
lambda | 람다
binding | 바인딩
generic | 제네릭
capture | 포착하다
hierarchy | 계층
signaling | 신호전달
flow | 흐름
Derive | 파생하다
traceback | 역추적
transferred | 양도된
chaining | 체이닝
raise | 떠오르다
format | 포맷, 양식
disguise | 가장하다
clause | 절
cleanup | 코드 정리, 정리
propagate | 전파하다
logging | 로깅
introspection | 검사
masking | 마스킹
reliably | 신뢰성
transaction | 트랜잭션
connection | 연결
manager | 관리자
acquire | 획득하다
release | 출시하다, 해제하다.
reachable | 도달가능한
unicode | 유니코드
object | 오브젝트, 객체
byte(s) | 바이트
sequence | 시퀀스
active | 활성화 된
experimentation | 실험적인 시도, 실험
refactory | 리팩토리
type checker | 타입 체커
preference | 설정
stub | 스텁
repository | 저장소
linter | 린터
side | 항

</google-sheets-html-origin>

**Comment by hajun-myoung** [comment]
@Sumin0916 @zerosheepmoo 2차 검토 코멘트 모두 달았습니다~ Programming Recommendations 문서는 양이 굉장하네요... 😢 
확인 부탁드려요!

**Comment by Sumin0916** [comment]
## 3차 검토 완료

일부 오탈자, 약간의 단어 표현 수정 완료하였습니다!
의견 부탁드립니다 :)

**Comment by zerosheepmoo** [comment]
@Sumin0916 디스커션에 남긴 내용들을 종합해주시면 좋을 것 같습니다. :)

**Comment by hajun-myoung** [comment]
확인했습니다. 72번 줄 람다 표현식과 관련된 내용이 번역 오류일줄은 생각도 못했네요..!
나머지 주신 코멘트들은 대부분 좋은 이견이었습니다. 😄

**Comment by zerosheepmoo** [comment]
@Sumin0916 
이 코멘트들 확인 후 커밋 후 클로즈해주세요! ㅎㅎ
