### ISSUE TITLE
[notice] 3차 검토에 관한 정책

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/pep8-in-korean#45]
## 내용

- #10 에 의한 정책은 유지하면서, #38 을 적용하는 방안
- 3차 검토는 **중복 검토하여도 무관**하며 다음에 대해 중점적으로 검토한다.
  - 전체적인 문맥(readability 및 understandability)
  - 마크다운 스타일 가이드 형식
  - 자잘한 실수(오타)

모두가 이 이슈에 reaction 을 하면 클로즈합니다 :)

**Comment by Ohjiwoo-lab** [comment]
해당 내용에 대해 동의합니다!!

**Comment by Sumin0916** [comment]
- 내용 숙지하였습니다!
