### ISSUE TITLE
PEP8 번역 - A Foolish Consistency is the Hobgoblin of Little Minds

### ISSUE THREAD

**Issue by Sumin0916** [zerosheepmoo/pep8-in-korean#7]
## 참여자
- 번역: @Sumin0916 
- 검토
  - 1차: @zerosheepmoo
  - 2차: @hajun-myoung 
  - 3차: @zerosheepmoo

**Comment by zerosheepmoo** [comment]
## 2차 리뷰어 분께

가독성 향상을 위해 다음과 같은 번역은 어떨까 제안합니다.

> ~~Guido의 핵심 인사이트 중 하나는 코드는 쓰여진 양보다 읽히는 양이 훨씬 더 많다는 것이다.~~ 실수로 제가 적용했으니 맘에 안들면 알려주세요.

> 이 가이드는 코드의 가독성을 향상시키고,

**Comment by zerosheepmoo** [comment]
# 단어 목록 추출

- consistency: 일관성
- spectrum: 스펙트럼
- readability: 가독성
- recommendation(s): 권장 사항
- backward compatibility: 하위 호환성
- key: 핵심, 키

**Comment by zerosheepmoo** [comment]
# 3차 검토 내역

> 이 스타일 가이드에 맞춰 일관성을 지키는 것은 중요하다.
> 하지만, 프로젝트 내의 일관성을 지키는 것은 더 중요하며,
> 한 모듈 또는 함수 내에서의 일관성은 무엇보다도[^1] 중요하다.
>
> [^1]: _역: 방금 언급한 둘보다도_

- 문단이 부드럽지 못해 추가적인 접속어와 역자 주를 추가하였습니다. 역자 주는 제 생각엔 footnote 로 옮겨도 좋을 것 같습니다.

> 다른 예시들을 보고 무엇이 가장 좋은지 결정하자.

- 동어반복 `최선`이 어색하여 표현을 바꾸었습니다.

> 가이드를 적용시키는 것이 가독성을 떨어뜨릴 때. 심지어 이 PEP 를 준수하는 코드를 읽는데 익숙한 사람도 읽기가 힘들 때.

- 문장의 가독성 향상을 위해 분리하였습니다.

> 코드와 스타일 가이드가 권장하는 기능(feature)을 지원하지 않는 이전 버전의 Python 이 호환되어야 하는 경우.

- `지침`은 다소 왜곡된 의미전달의 가능성이 높습니다. feature를 기능으로 번역합니다. feature 뒤에 영문을 같이 작성하므로써 feature 의 본 의미를 전달하는데 어려움이 없으면 좋겠습니다.

**Comment by zerosheepmoo** [comment]
모두 동의하시면 클로즈하겠습니다.

**Comment by Sumin0916** [comment]
확인했습니다 동의합니다!

**Comment by hajun-myoung** [comment]
## 제안
이건 어떨까요?

> 가이드를 적용시키는 것이 가독성을 떨어뜨릴 때. 심지어 이 PEP 를 준수하는 코드를 읽는데 익숙한 사람도 읽기가 힘들 때.

가이드를 적용시키는 것이 가독성을 떨어뜨릴 때. 심지어 이 `PEP를` 준수하는 코드를 읽는데 익숙한 사람`조차도` 읽기가 힘들 때

- `PEP를` : 조사를 붙여주는 게 더 자연스러운 것 같아요.
- 사람`조차도` : 사람`도`와 큰 차이는 없지만, 의미를 강조하는 건 어떨까 싶어서 여쭤봐요.

*나머지 검토된 항목*에는 모두 동의합니다. 의미가 훨씬 잘 전달되는 것 같아요!

**Comment by zerosheepmoo** [comment]
@hajun-myoung 
- 조사 붙이는 것에 동의합니다.
- `조차도` 가 가독성을 향상 시키진 않는 것 같습니다. 전 반대합니다.

@Ohjiwoo-lab 님은 어떠신가요?

**Comment by Ohjiwoo-lab** [comment]
## 의견
- `적용시키는` 을 `적용하는` 으로 했으면 좋겠습니다.
- 흠...저는 `조차도`로 했을 때 의미가 강조되는 느낌이 있어서 좋은 것 같습니다 :)
- 조사를 붙이는 것에도 동의합니다!

> 가이드를 적용하는 것이 가독성을 떨어뜨릴 때. 심지어 이 PEP를 준수하는 코드를 읽는데 익숙한 사람조차도 읽기가 힘들 때.
