### ISSUE TITLE
PEP8 번역 - Code Lay-out - indentation

### ISSUE THREAD

**Issue by Ohjiwoo-lab** [zerosheepmoo/pep8-in-korean#8]
# 참여자
- 번역 : @Ohjiwoo-lab
- 검토 
  - 1차: @zerosheepmoo
  - 2차: @Sumin0916 
  - 3차: @zerosheepmoo

**Comment by Ohjiwoo-lab** [comment]
# Indentation 1차 검토
Code Lay-out에 챕터가 많아서 이에 대한 피드백을 먼저 주셨으면 합니다.
continuation line과 *multiline* 이라는 단어에 대해 여러 줄에 이어지는 문장으로 해석하였는데 어색하지 않는 지 봐주셨으면 합니다.
처음하는 번역이라 어색한 부분이 많이 있을 거 같아 요청드립니다..

**Comment by zerosheepmoo** [comment]
## 그렇다면...

이슈 분리를 통해 작업단위를 쪼개는 것이 좋겠습니다. 
만약 지금처럼 번역 중간에 검토요청을 하게되면,
제가 1차 검토를 완료하더라도 2차검토요청을 넣기가 힘들게 됩니다.
후에 뒷부분을 번역했을 때 커밋이력을 봐야 어디까지 했는지 알게되는 것도 불편하고요 ㅎㅎ
이슈 제목을 Code Layout  -indetation 이렇게 변경하도록 하고 후에 코드 수정은 다른 이슈로 태그하도록 합시다.

**Comment by Ohjiwoo-lab** [comment]
넵 알겠습니다!!

**Comment by zerosheepmoo** [comment]
@Ohjiwoo-lab 네, 검토 논의를 위한 코멘트를 전부 달았습니다. 시간이 날 때 확인해주세요.
코멘트에 대해 동의하실 경우 답 코멘트를 남겨주시고, 아닐 경우 의견 코멘트를 달아주세요:)

**Comment by Ohjiwoo-lab** [comment]
모두 확인하였습니다! 역시 고칠 부분이 많네요.. 중간에 '스페이스'를 '공백'으로 바꾸는 comment 달았으니 그것만 확인해주시면 될 거 같아요!

**Comment by zerosheepmoo** [comment]
## :)
- 감사합니다. 외에 논의사항이 더 없다면 해당 코멘트대로 제가 수정하겠습니다.
- 고칠 부분이라고 너무 낙심마시고 다른 의견이라고 생각해주세요. 우리는 의견교환을 거쳐 더 좋은 용어를 선택한 것이지요!

**Comment by Ohjiwoo-lab** [comment]
넵!알겠습니다 감사합니당!

**Comment by Sumin0916** [comment]
- 2차 검토도 완료하였습니다 확인 부탁드립니다!

**Comment by zerosheepmoo** [comment]
@Sumin0916 
다음에 동의합니다.
- 필요하다로 고치는 것
- 추가적인 들여쓰기만 반영하는 것

단지, 1차 검토한 commit 인 `ca2f0dc` 에 달아주셨으면 더 좋았을 것 같습니다!

**Comment by Sumin0916** [comment]
앗,,, 다음부턴 앞선 검토 commit에 리뷰를 달아야겠군요! 확인하였습니다!

**Comment by Sumin0916** [comment]
내어쓰기(hanging indent) 주석 번역이 되어있지 않아서 번역을 추가로 진행하였습니다!

**Comment by zerosheepmoo** [comment]
# 3차 검토 사항

## 정정내용

> 각 들여쓰기 레벨마다 4칸 공백을 **사용하자.** 

- 번역 전문의 일관성을 위해 명령문은 `~하자` 형태로 번역한다.

> 여러 줄에 이어지는 문장에서는 괄호 안의 Python의 암시적 줄 결합을 사용하여 
> 괄호들로 감싸진 요소들의 세로줄을 맞추어야 한다.
> 또는 *내어쓰기*를 사용하여 세로줄을 맞추어야 한다.

- 암시적 줄결합은 의미가 분명하므로 영문을 적을 이유가 없다.
- `wrapped ~ inside`: 전체적인 문맥을 고려할 때, 가독성 향상을 위해 `괄호들로 감싸진`이 적절하다.
- 문장이 너무 길기 때문에 분리한다.
- `'줄'은 명사로 띄어 씀이 바르나, '고무줄', '빨랫줄' 등 다수 단어는 합성어로 보아 붙여 씁니다.`
- 내어쓰기에 대한 설명은 각주에서 충분히 설명되고 있으므로 영문을 적을 이유가 없다.
- 문장의 응집성을 위해 `정렬한다` 대신에 세로줄을 맞추어야한다로 적습니다.

> 내어쓰기를 사용할 때는 고려해야 할 사항이 있다.
> 우선, 첫 번째 줄에는 아규먼트가 없어야한다.
> 그리고 추가적인 들여쓰기는 여러 줄에 이어지는 문장 자체를 구분하는 데에 사용되어야 한다.

- `특히` 는 불필요하고 가독성을 해친다.
- `다음 ~` 의 표현은 사실 영어식 표현이다. 본래 직역이 원칙이지만 가독성을 위해 각 문맥마다 적절한 번역을 하자.
- [국립 국어원 첫 번째 띄어쓰기](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=128957)
- 문장은 잘못된 번역이다. 특히, 언어 구조에 있어 statement clause phrase line 모두 별개의 개념이므로 유의바람.
- 불필요한 미사여구 `~으로서`, `분명하게`는 제거한다.

> ```python
> # 옳은 예
>
> # 열린 구분 문자(역: 여기서는 소괄호)를 기준으로 세로줄을 맞춘다.
> ...
> # 함수의 아규먼트와 나머지 부분을 ...
> # 내어쓰기는 레벨을 더해야 한다. (역: 나머지 줄에 들여쓰기를 해야 한다는 의미)
> ...
> ```
>
> ```python
> ...
> # 세로줄을 맞추지 않았을 때, 첫 번째 줄에 아규먼트는 없어야 한다.
>
> ```

- 전문 응집성 향상을 위한 올바른 => 옳은
- 주석 내 역자 주 표시
- 가독성 향상을 위해 순서 바꿈
- 경어체 => 낮춤말
- `요소`, `문장`보단 `줄`이 가독성 향상, 또는 적절한 설명
- 존재하지 않아야 한다 => 없어야 한다.

> `::` 삭제

> `선택사항:` 삭제

- 콜론(:)을 사용하는 문장은 영어식이므로 제거

> (역: 여기서는 2칸 공백 들여쓰기 규칙이 적용되었다.)
> ...
> `if 조건문에서의 여러 줄에 이어지는 문장` 삭제

- 응집성 향상을 위해 바로 윗 줄의 문장과 대응 시켰다.
- if 이하의 문장은 은 원문에 포함 안되어 있다.

> `if` 문의 조건 부분이 길어 여러 줄로 작성 될 필요가 있을 때,
> 두 문자 키워드(즉, `if`)에 한 칸 공백과 열린 소괄호를 더하는 결합이
> 나머지 여러 줄로 작성 된 조건 부분에
> 자연스러운 4칸 공백 들여쓰기를 할 수 있게 만드는 것에 주목해야한다.
> 그런데 이는 `if`-문 내 중첩되어 있는 코드 모음과 시각적인 충돌을 일으킬 수 있다.
> (이 코드 모음은 자연스럽게 4칸 공백으로 들여쓰기 된 코드 모음이다.)
> 이 PEP 문서에서는 `if`-문 내 중첩되어 있는 문장으로부터
> 이러한 조건 부분에 대해 시각적으로 어떻게 추가적인 구별을 할 것인지
> (또는 구별을 할 것인지 하지 않을 것인지)에 대한 명백한 입장이 없다.
> 이런 상황에서 혀용 가능한 선택을 제시하되, 제한하지는 않을 것이다.

- 가독성 향상을 위해 불필요한 단어를 제외 시키고 문장의 순서를 바꿈.
- 번역 오류를 수정함. 결합 이하의 절은 plus 이하의 구까지 모두 포함하는 서술절임.
- 문장 나누기를 함

> ```python
> # 구문 하이라이터(syntax highlighter)를 지원하는 에디터에서
> # 구별할 수 있게 주석을 더하기
>...
> # 여러 줄에 이어지는 조건 줄에서 추가적인 들여쓰기를 한 경우
> ```

- 자연스러운 번역으로 수정

> (이항 연산자의 앞뒤로 띄어쓰기를 할 것인지에 대한 논의를 아래의 섹션에서 확인할 수 있다.)
>
> 여러 줄 구조에서 닫힌 괄호들은 리스트의 마지막 줄
> 공백이 아닌 첫 번째 문자를 기준으로 세로줄을 맞출 수 있다.

- 문장길이 줄임
- 여기서는 챕터단위가 아닌 섹션단위임. 다른 부분에서 섹션이라고 명시되어 있는 문장들을 찾아볼 수 있음.
- multiline 은 이어지는 의 의미가 없어야함
- under 기준으로로 번역되어야 옳음.

**Comment by zerosheepmoo** [comment]
> 아무리 읽어봐도 

if 문의 조건 부분이 길어 여러 줄로 작성 될 필요가 있을 때,
두 문자 키워드(즉, if)에 한 칸 공백과 열린 소괄호를 더하는 결합이
나머지 여러 줄로 작성 된 조건 부분에
자연스러운 4칸 공백 들여쓰기를 할 수 있게 만드는 것에 주목해야한다.
그런데 이는 if-문 내 중첩되어 있는 코드 모음과 시각적인 충돌을 일으킬 수 있다.
(이 코드 모음은 자연스럽게 4칸 공백으로 들여쓰기 된 코드 모음이다.)
이 PEP 문서에서는 if-문 내 중첩되어 있는 문장으로부터
이러한 조건 부분에 대해 시각적으로 어떻게 추가적인 구별을 할 것인지
(또는 구별을 할 것인지 하지 않을 것인지)에 대한 명백한 입장이 없다.
이런 상황에서 혀용 가능한 선택을 제시하되, 제한하지는 않을 것이다.

> 의 부분이 가독성이 너무 떨어지는 것 같습니다.

> 다음과 같이 추가 수정합니다.

`if`-문의 조건 부분이 길어 여러 줄로 작성 될 필요가 있는 경우를 보자.
`if` 키워드에 한 칸 공백과 열린 소괄호를 붙여 작성하면,
나머지 여러 줄로 작성 된 조건부가 저절로 4칸 공백 들여쓰기 되는 것에 주목해야 한다.

이는 if-문 내 중첩되어 있는 코드 모음과 시각적인 충돌을 일으킬 수 있다.
(이 코드 모음도 4칸 공백 들여쓰기가 되어 있을 경우)

이 PEP 문서에서는 if-문 내 중첩되어 있는 문장으로부터
이러한 조건 부분에 대해 시각적으로 어떻게 추가적인 구별을 할 것인지
(또는 구별을 할 것인지 하지 않을 것인지)에 대한 명백한 입장이 없다.
이런 상황에서 혀용 가능한 선택을 제시하되, 제한하지는 않을 것이다.

> 문장을 많이 고치고 단락을 나누었습니다.

**Comment by zerosheepmoo** [comment]
## 단어목록 추출

- Continuation lines: 여러 줄에 이어지는 (문장)
- wrapped: 감싸진, 둘러싸인, 래핑된
- consider: 고려하다.
- argument(s): 아규먼트
- line: 줄
- deliminator: 구분 문자 - [한국어 위키](https://ko.wikipedia.org/wiki/%EA%B5%AC%EB%B6%84_%EB%AC%B8%EC%9E%90)
- optional: 선택 사항
- multiline: 여러 줄
- statement: 문, 문장
- write: 작성하다.
- create: 생성하다. 만들다.
- suite: 모음, 슈트(테스트 관련일 때)
- syntax highlighter: 구문 하이라이터
- editor: 에디터
- section: 섹션
- opening: 열린
- closing: 닫힌
- explicit: 명시적인
- implicit: 암시적인
- 주석의 `correct`: 옳은 예
- 주석의 `wrong`: 잘못된 예

단어 추출까지 완료하였습니다. 이의가 없다면 모든 분들의 동의하에 해당 이슈를 클로즈하겠습니다.

**Comment by Sumin0916** [comment]
가독성이 많이 좋아진 것 같습니다 동의합니다!

**Comment by Ohjiwoo-lab** [comment]
저도 동의합니다 :)
