### ISSUE TITLE
[전체] 공통단어 사용하기

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/pep8-in-korean#9]
## 문제

번역에도 일관성을 지켜야합니다. 문제는 우리가 너무 각자 다른 언어를 쓰고 있다는 거죠...
각 용어마다 적절한 번역이 필요하며 이는 일관성이 있어야합니다.
우리는 각 영어단어마다 뜻을 정리한 표가 필요합니다!

우리는 [javascript.info 한국어 번역 프로젝트의 스프레드시트](https://docs.google.com/spreadsheets/d/1fYaEI8vz26N3R2VaxrlNnk9fMQ8zIy4RpvjRp4jZd0Q/edit#gid=0)를 벤치마킹할 것입니다!

그리고 이러한 스프레드시트의 관리는...
괜찮으시다면 지금 번역 기여를 가장 열심히 하고 계신 @Sumin0916 님께서 맡아주시면 너무 감사할 거 같아요 :D

@Sumin0916 님 드라이브에 생성 후 수정 권한을 번역을 함께하고 있는 분들께 드리고,
수정 권한이 없는 공개링크를 만드는 것이 좋겠습니다.

**Comment by Sumin0916** [comment]
넵! 제가 추후에 스프레드시트 링크를 만들어서 공유하도록 하겠습니다
후에 링크는 어디에 공지하면 괜찮을까요?

**Comment by zerosheepmoo** [comment]
@Sumin0916

README.md 에 누구나 확인을 할 수 있도록 달아주시면 좋을 것 같습니다.
처음 또는 마지막에 안내 또는 참고 헤딩을 달아두시면 좋을 거 같아요.

**Comment by Sumin0916** [comment]
넵 확인하였습니다!

**Comment by zerosheepmoo** [comment]
현재 공유링크가 공개 되어있고, 같이 작업하시는 분들 모두 부여된 상태니 해당 작업은 끝난 것으로 간주하고 이슈를 클로즈합니다.
필요 시 재오픈 합니다.
